### ISSUE TITLE
Uncaught TypeError after d3-selection update

### ISSUE THREAD

**Issue by daveisfera** [upsetjs/venn.js#13]
Thanks for the quick turnaround of #7 but we're now having a new issue and we're getting the following error:
```
Uncaught TypeError: exit.selectAll(...).attrTween is not a function
    at chart (venn.esm.js:1332)
    at MyVennChart.componentDidUpdate (index.jsx:45)
    at MyVennChart.componentDidMount (index.jsx:22)
    at commitLifeCycles (react-dom.development.js:20663)
    at commitLayoutEffects (react-dom.development.js:23426)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994)
    at invokeGuardedCallback (react-dom.development.js:4056)
    at commitRootImpl (react-dom.development.js:23151)
    at unstable_runWithPriority (scheduler.development.js:646)
```

**To Reproduce**

1. Update to 1.4.0
2. Load `VennDiagram`
3. Observe above error

**Expected behavior**

`VennDiagram` would load as it did with 1.4.0

**Context**

- Version: 1.4.0
- Browser: Safari 14.0.3

**Comment by sgratzl** [comment]
D3 is not longer directly imported by venn.js. It is just a optional dependency since it solely takes the input d3 object and operates on that.

So, in your case, can you confirm that, when calling venn.js, the given d3 object has the `attrTreen` or in general `.transition` object().

e.g.,
```
const chart = venn.VennDiagram();
d3.select('#venn').transition()
d3.select('#venn').datum(sets).call(chart);
```

**Comment by daveisfera** [comment]
That makes sense, but this error happens when running the examples that are listed in the readme, so I think that there's an incompatibility with the update to `d3-selection` and the current code

**Comment by sgratzl** [comment]
I still don't see how this is a bug within the library:

see also https://codesandbox.io/s/eager-gareth-zjyjd?file=/src/index.ts

**Comment by daveisfera** [comment]
I can see that code pen working, so it appears the underlying module is doing the right thing, but our current usage is based on the examples, so any advice on the changes we need to make to get it to work?

**Comment by sgratzl** [comment]
are you importing `import 'd3-transition'`? Tho, it creates a side effect which might be removed during bundle optimination

**Comment by daveisfera** [comment]
No, we aren't importing `d3-transition` and are only using `d3-selection` to change styling, tooltips and handle events.

**Comment by sgratzl** [comment]
I just released v1.4.1 which checks whether the given d3 selection object has the possibility to render transitions. if it has it will use it to render animations else it won't animate things.

**Comment by daveisfera** [comment]
Thanks for the help on that and with that update it's no longer crashing, but now the tooltips don't work because they also don't have a `transition`, so any advice on getting that to work?

**Comment by sgratzl** [comment]
why cannot you just also `import 'd3-transition'` when importing `d3-selection`?
