### ISSUE TITLE
Color scheme isn't maintained when changing number of circles drawn

### ISSUE THREAD

**Issue by Mojito88** [upsetjs/venn.js#14]
Hi Samuel,
first and foremost thank you for maintaining this library.

Anyway, I've noticed that the color scheme of the circles is not maintained when switching from venn with 4 circles to less circles and back to the original number. 

Instead, it seems that it keeps track of the last color scheme and applies that to the new set of circles. 

Is it fixable somehow?

**Comment by sgratzl** [comment]
have you tried setting the color directly for each set?

as in 
```
const sets = [
  { sets: ['A'], size: 12, color: 'red' },
  { sets: ['B'], size: 12, color: 'blue' },
  { sets: ['A', 'B'], size: 2, color: 'green' },
];
```

**Comment by Mojito88** [comment]
I think this is impractical as a solution in my specific case, because sets are generated in a view and then passed to the html page in django in an iterative way across the data. 
I was using the colorScheme feature directly in the VennDiagram function call, and thought it would be self adjusting for the number of circles drawn, which is not apparently.

**Comment by sgratzl** [comment]
create you create a codepen illustrating the problem, please

**Comment by Mojito88** [comment]
https://codepen.io/mojito88/pen/QWGGKQE

Sorry took a little bit longer but this should work.
As you can see, if you switch from 4 circles to 3 or 2 and go back to those with a higher number of circles, the color scheme does not remain the original one.

**Comment by sgratzl** [comment]
why are you creating a new instance of VennDiagram all the time? Thus, the instance will forget its existing color assignments.

if I move the instantiation out, it works as expected:

https://codepen.io/sgratzl/pen/rNWWMKY?editors=0010

![out](https://user-images.githubusercontent.com/4129778/107637775-f6568600-6c6e-11eb-9a7e-c9a4fbe2d15b.gif)

**Comment by Mojito88** [comment]
Thank you, it was just a noob question then, sorry to bother you.
However, when i move the instantiation out of the function in my code, from the console i get that "venn is not defined" and nothing gets plotted, while when inside the function everything works as in my codepen. Don't know why this happens tbh
