### ISSUE TITLE
Is it possible to highlight all possible intersection?

### ISSUE THREAD

**Issue by Jimmy-A-Caroli** [upsetjs/venn.js#15]
Hi Samuel,

as title says, is it possible to separately highlight all possible intersection, like in venny-like venn diagram?

I report here your codepen from my previous question: https://codepen.io/sgratzl/pen/rNWWMKY?editors=0010

My question is if it is possible, for example, to highlight the section of group D that is not shared with any other circle, or the section shared by A and C but not with B and D. 

Hoping that the question is as clear as possible.
Thanks

**Comment by sgratzl** [comment]
take a look at https://upset.js.org/venn.js/examples/customLayoutDistinct.html. The more complex it gets, the easier it is to do the rendering manually.
