### ISSUE TITLE
intersectionArea function does not account for extremely small amounts of overlap

### ISSUE THREAD

**Issue by snoozbuster** [upsetjs/venn.js#22]
When you have two sets such that `A ⊃ B`, in rare cases this function generates a non-overlapping intersection area for A, even though it should be entirely contained within B. (I may have that backwards wrt the notation I used.) I think this is because [this line](https://github.com/upsetjs/venn.js/blob/main/src/circleintersection.js#L101) (or maybe [this one](https://github.com/upsetjs/venn.js/blob/main/src/circleintersection.js#L110), or maybe even both) compares the radii of the two circles without taking into account the `threshold` for float comparisons.

**Comment by sgratzl** [comment]
do you have an example that I can use to reproduce this bug?

**Comment by snoozbuster** [comment]
unfortunately, no - this was discovered by an intern a few months ago who "had some data on a post it note he fed in and played with the decimals until he could reproduce it." We did debug it to around here and concluded it was an epsilon comparison error, but we were maintaining our own venn.js patches at the time so we filed a ticket (which I found recently) to come back to it. (the ticket is still open, so it's possible someone from my team will come fix it later on, but figured I would post it here in case anyone else could find and fix it sooner)
