### ISSUE TITLE
Simple Example is broken at upset.js.org...

### ISSUE THREAD

**Issue by deftdawg** [upsetjs/venn.js#36]
When I click on view simple example from: 
https://upset.js.org/venn.js/examples/simple.html

Other examples are working.

Browsers: Chrome and Safari, OSX

Developer Tools -> Console gives the following:
```
[Error] TypeError: null is not an object (evaluating 'this.node().__data__')
	datum (d3.v4.min.js:2:107107)
	chart (venn.js:1744)
	call (d3.v4.min.js:2:103728)
	Global Code (simple.html:27)
```

**Comment by sgratzl** [comment]
should be fixed ß: https://upset.js.org/venn.js/examples/simple.html
