### ISSUE TITLE
Multiple label support

### ISSUE THREAD

**Issue by projectje** [upsetjs/venn.js#4]
Would it be possible to have multiple labels per area? As far as i can see i should do 

sets: ['Information', 'Things That Overlap'], size: 4, label: 'Redundancy' },

But I want to fully generate something like http://3.bp.blogspot.com/-3Lufulseck4/UWF6MsaAosI/AAAAAAAAEk8/T8FNhnLbUug/s1600/ZghIM4Sh.jpg and make each of the words clickable hyperlinks.

**Comment by sgratzl** [comment]
you can use the `layout` method to compute just the layout and do the rendering yourself. see https://github.com/upsetjs/venn.js#custom-d3-rendering. However, adding labels such that they fit the shape of the slice is a different topic not covered by this library.
