### ISSUE TITLE
Ellipses in Euler diagrams

### ISSUE THREAD

**Issue by karlmakepeace** [upsetjs/venn.js#42]
*Previously posted issue in "[upsetjs/upsetjs_r](https://github.com/upsetjs/upsetjs_r/issues/33#issue-1468918095)"*

It would be great if the Euler diagram functions supported ellipses (e.g.: [`eulerr` package](https://cran.r-project.org/web/packages/eulerr/index.html)) as they allow for less error in the the set area representation ([link](https://cran.r-project.org/web/packages/eulerr/vignettes/introduction.html) includes explanation & example(s)).

e.g. Euler plot constructed with ellipses (pasted from [link](https://cran.r-project.org/web/packages/eulerr/vignettes/introduction.html)):

![image](https://user-images.githubusercontent.com/6200041/204684353-aaeaabdb-673a-4e40-9549-e11d1506e721.png)

**Comment by sgratzl** [comment]
wontfix no time
