### ISSUE TITLE
How do we set the size?

### ISSUE THREAD

**Issue by lloydjatkinson** [upsetjs/venn.js#45]
The following code produces a SVG with a size of 600x350:

```ts
const sets = [
    { sets: ['A'], size: 12 },
    { sets: ['B'], size: 12 },
    { sets: ['A', 'B'], size: 2 },
];

var chart = venn.VennDiagram();
// @ts-expect-error Incorrect typings
d3.select(container).datum(sets).call(chart);
const svg = svgDocument.body.toString();

console.log(svg);
```

How do we set the size of the SVG? There is no option for it in the `VennDiagram` function.

**Comment by sgratzl** [comment]
the returned venn diagram instance (in your example `chart` has numerous options including `.width()` and `.height`.  see also export interface IVennDiagram {
