### ISSUE TITLE
Invisible triple intersection

### ISSUE THREAD

**Issue by omkarshelar** [upsetjs/venn.js#6]
Hi Samuel,
Appreciate you maintaining this library...
Any progress or ways to handle issue #141 in the original library?

https://github.com/benfred/venn.js/issues/141

**Comment by sgratzl** [comment]
atm the library just take 1 and 2 set intersections into account. While in theory you can extend to add more combinations, it becomes less likely that the layout will converge to a good layout. For example the image from the original issue, I don't actually know how it should look like that it fulfills all the constraints.

**Comment by sgratzl** [comment]
closing since stale and no feedback
