### ISSUE TITLE
Update d3-selection and d3-transition to modular implementation

### ISSUE THREAD

**Issue by daveisfera** [upsetjs/venn.js#7]
[d3 moved to a modular design](https://github.com/d3/d3/releases/tag/v4.0.0), so it would be great if [d3-transition could be updated to the 2.x line](https://github.com/d3/d3-transition/releases/tag/v2.0.0) and the [same with d3-selection](https://github.com/d3/d3-selection/releases/tag/v2.0.0)

**Comment by sgratzl** [comment]
fixed with https://github.com/upsetjs/venn.js/releases/tag/v1.4.0
