### ISSUE TITLE
Remove `@babel/runtime` from dependencies

### ISSUE THREAD

**Issue by daveisfera** [upsetjs/venn.js#8]
`@babel/runtime` is specified as a dependency but it's not directly used and shouldn't be a dependency.

**To Reproduce**
Install `@upsetjs/venn.js`

**Expected behavior**
`@babel/runtime` is not installed when installing `@upsetjs/venn.js`

**Context**

- Version: 1.3.0
- Browser: Safari 14.0.3

**Comment by sgratzl** [comment]
fixed with https://github.com/upsetjs/venn.js/releases/tag/v1.4.0
